# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6ef8a96655ffd294efd7f59c179bdfb2ac90780ae3080d8b2bc67423f227257e46a03d929c6b245624bcdb543e0740d70efa068ae7ea56f9a39612b4c59e20a

test:
  secret_key_base: 341e76dd36a7d8545dddf4a6979cdb924fad7c3b148dfc0879dc9393af5c080c59d58648219bd4aeb793a81fe4e4c393d1238c990c483017c6fefe0a205359d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
